            - name: Fork Sync2
  # You may pin to the exact commit or the version.
  # uses: zwping/fork-sync@7ad9681518d04008cc8f056abed8fefc2902e96d
  uses: zwping/fork-sync@v1.6.5
  with:
    # Owner of the forked repository
    owner: # optional
    # Token for the github API
    token: # optional, default is ${{ github.token }}
    # Branch to track
    head: # optional, default is master
    # Branch to keep updated
    base: # optional, default is master
    # Merge method to use
    merge_method: # optional, default is merge
    # The title of the pull request
    pr_title: # optional, default is Fork Sync: Update from parent repository
    # The message in the pull request
    pr_message: # optional
    # Ignore Exceptions
    ignore_fail: # optional
    # Automatically approve pull request before merge
    auto_approve: # optional
    # Automatically merge the pull request
    auto_merge: # optional, default is true
    # Retry count
    retries: # optional, default is 4
    # Delay amount between retries
    retry_after: # optional, default is 60

    name: Sync Fork

on:
  push:
    branches:
      - "sync-fork"
  schedule:
    - cron: '0 0 * * *' #every 24h
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4
        with:
          repository: rhelou/helousound
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/NSDesignllc/helousound.git
          git fetch upstream

      - name: Sync with upstream/main
        run: |
          git fetch upstream main
          git checkout -B main origin/main
          git merge upstream/main
          git push origin main

      - name: Clean up
        run: |
          git remote remove upstream
